version: 0.1.0-{build}
skip_tags: true

init:
  - ps: >-
      if ($env:Enable_RDP -eq 1) {
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }

install:
  - git submodule update --init --recursive
  - ps: cinst hugo --version 0.30

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

build_script:
  - cd Source
  - hugo

after_build:
  - cd ../
  - 7z a artifacts\portfolio-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Source\public\**

artifacts:
  - path: artifacts\*.zip
    name: webroot
