[build]
  base = "Source"
  command = "hugo"
  publish = "Source/public"

[build.environment]
  HUGO_VERSION = "0.38"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Robots-Tag = "none"
    Content-Security-Policy = "default-src 'self'; script-src 'self' www.googletagmanager.com code.jquery.com cdnjs.cloudflare.com stackpath.bootstrapcdn.com 'sha256-8PUO3fXlSy7+r1yeLssICja31dL1U8OY4e3Qtn0BGUc='; style-src 'self' *.cloudfront.net fonts.googleapis.com; img-src 'self' *.cloudfront.net; font-src 'self' fonts.googleapis.com fonts.gstatic.com *.cloudfront.net; form-action 'self'; manifest-src 'self'"
    Referrer-Policy = "strict-origin-when-cross-origin"
