[build]
  base = "Source"
  command = "hugo"
  publish = "Source/public"

[build.environment]
  HUGO_VERSION = "0.38"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    X-Robots-Tag = "none"
    Content-Security-Policy-Report-Only = "default-src 'self'; script-src 'self' googletagmanager.com code.jquery.com cdnjs.cloudflare.com stackpath.bootstrapcdn.com sha256-VQ1L8YSkuJ0+rULjUAVvcMwqQxkIUuK3m13wSzILmBg=; style-src 'self' cloudfront.net; img-src 'self' cloudfront.net; font-src 'self' fonts.googleapis.com; form-action 'self'; manifest-src 'self'"
    Referrer-Policy = "strict-origin-when-cross-origin"
