name = "Portfolio"
description = ""
homepage = "http://www.jamescoxhead.co.uk/"
tags = []
features = []
min_version = "0.30"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
