---
baseURL: "http://example.org/"
languageCode: "en-gb"
title: "Portfolio - James Coxhead"
theme: "Portfolio"
disableKinds: ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]
enableRobotsTXT: true
metaDataFormat: "yaml"
googleAnalytics: "UA-12345"
---
