---
baseURL: "http://example.org/"
languageCode: "en-gb"
title: "Portfolio - James Coxhead"
theme: "Portfolio"
disableKinds: ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]
enableRobotsTXT: true
metaDataFormat: "yaml"

params:
  personal: "https://www.jamescoxhead.co.uk"
  linkedin: "https://www.linkedin.com/in/jamescoxhead/"
  github: "https://github.com/jamescoxhead"
---
